apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: my-postgres
  name: my-postgres
spec:
  ports:
  - name: "5439"
    port: 5439
    targetPort: 5432
  selector:
    io.kompose.service: my-postgres
status:
  loadBalancer: {}
