apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: my-postgres
  name: my-postgres
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: my-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_USERNAME
          value: postgres
        image: postgres
        name: my-postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
